// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAODvZX-grUOmuhwIPtv_j_-6GU3p3fViw',
    appId: '1:413426935515:web:71f4d8a546c5b3bbe90efe',
    messagingSenderId: '413426935515',
    projectId: 'school-maps-e69f3',
    authDomain: 'school-maps-e69f3.firebaseapp.com',
    storageBucket: 'school-maps-e69f3.firebasestorage.app',
    measurementId: 'G-CY29SJFPC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzOX3ZIFVWnD7gDB4eqgVlcNqf013btD0',
    appId: '1:413426935515:android:13d412bd7967fb44e90efe',
    messagingSenderId: '413426935515',
    projectId: 'school-maps-e69f3',
    storageBucket: 'school-maps-e69f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyRA9khfSHayUTjkkweZqNAl42oRNJl48',
    appId: '1:413426935515:ios:44f10b9ea51ffd1ee90efe',
    messagingSenderId: '413426935515',
    projectId: 'school-maps-e69f3',
    storageBucket: 'school-maps-e69f3.firebasestorage.app',
    iosBundleId: 'com.example.schoolMaps',
  );
}
